nelmio_api_doc:
    documentation:
        info:
            title: API Tweets microservice
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        # http://localhost:7777/api/doc/feed
        feed:
            path_patterns:
                - ^/api/v1/get-feed
        default:
            path_patterns:
                - ^/api(?!/doc(.json)?$)
