old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    # producers - это кто тот отправляет сообщение
    # обычно пишут producers в отдельном приложении и consumers в другом приложении
    producers:
        add_followers:
            connection:       default
            exchange_options: { name: 'old_sound_rabbit_mq.add_followers', type: direct }
    # consumers - это кто тот читает сообщение
    consumers:
        add_followers:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.add_followers', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.add_followers' }
            callback: App\Consumer\AddFollowers\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
